# Generated by Django 5.0.1 on 2024-01-26 10:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='boardgame',
            name='authors',
            field=models.ManyToManyField(related_name='boardgames', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='boardgame',
            name='publisher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='boardgame', to='shop.publisher'),
        ),
    ]
