# Generated by Django 5.0.1 on 2024-01-08 13:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_rename_deployer_boardgame_publisher'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='boardgame',
            options={'ordering': ('name',)},
        ),
    ]
