# Generated by Django 5.0.1 on 2024-01-08 13:47

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_alter_boardgame_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='boardgame',
            name='authors',
            field=models.ManyToManyField(related_name='boardgame', to=settings.AUTH_USER_MODEL),
        ),
    ]
